development:
  adapter: postgresql
  encoding: unicode
  database: box_day_development
  pool: 20
  # username: box_day
  # password:

test:
  adapter: postgresql
  encoding: unicode
  database: box_day_test
  pool: 20
  # username: box_day
  # password:

production:
  adapter: postgresql
  encoding: unicode
  database: box_day_production
  pool: 20
  # username: box_day
  # password:
